### ISSUE TITLE
npm start script fails

### ISSUE THREAD

**Issue by josephmturner** [oipwg/trinity#81]
I receive the following error after 
`npm install` then `npm start`:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trinity@0.1.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trinity@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Is this an issue with the script?

**Comment by DevonJames** [comment]
hey @josephmturner we're actually about to make this repo private for a while, but if you'd be interested in testing this out with us, please join chat.alexandria.io

**Comment by josephmturner** [comment]
@DevonJames  Thanks! I have made an account - I look forward to seeing what y'all have been working on.
